name: Build fastapi-route-logger

on: ["push"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install pipenv
      run: python -m pip install pipenv

    - name: Run Build script
      run: |
        pipenv sync --dev
        pipenv run pytest

  check:
    needs: ci
    runs-on: ubuntu-latest
    outputs:
      version-updated: ${{ steps.changed-version-file.outputs.only_changed }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-version-file
        uses: tj-actions/changed-files@v12.2
        with:
          files: |
            .bumpversion.cfg

  build:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.version-updated == "true"

    steps:
      - uses: actions/checkout@v2

      - name: Get changed files
        id: changed-version-file
        uses: tj-actions/changed-files@v12.2
        with:
          files: |
            .bumpversion.cfg

      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install pipenv
        run: python -m pip install pipenv

      - name: Build Wheel
        run: |
          pipenv sync
          pipenv run python setup.py bdist_wheel

      - name: Publish distribution 📦 to Test PyPI
        if: startsWith(github.ref, 'refs/tags') != true
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
