name: Build fastapi-healthcheck

on: ["push"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install pipenv
      run: python -m pip install pipenv

    - name: Run Build script
      run: |
        pipenv sync --dev
        pipenv clean
        pipenv run pytest

  build:
    needs: [ci]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pipenv
        run: python -m pip install pipenv

      - name: Build Wheel
        run: |
          pipenv sync
          pipenv run python setup.py bdist_wheel

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
